[2020-09-11 19:32:13,031][werkzeug][INFO] -  * Running on http://127.0.0.1:8081/ (Press CTRL+C to quit)
[2020-09-11 19:33:39,349][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:39] "[37mGET /marked_image/undefined HTTP/1.1[0m" 200 -
[2020-09-11 19:33:39,352][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:39] "[37mGET /set_filter/none/all/none/no/none HTTP/1.1[0m" 200 -
[2020-09-11 19:33:39,428][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:39] "[37mGET /get_label_value_on_image/none/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:33:39,461][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:39] "[37mGET /marked_image/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:33:42,139][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:42] "[37mGET /marked_image/undefined HTTP/1.1[0m" 200 -
[2020-09-11 19:33:42,158][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:42] "[37mGET /set_filter/none/all/none/no/none HTTP/1.1[0m" 200 -
[2020-09-11 19:33:42,179][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:42] "[37mGET /get_label_value_on_image/none/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:33:42,182][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:42] "[37mGET /marked_image/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:33:42,732][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:42] "[37mGET /marked_image/undefined HTTP/1.1[0m" 200 -
[2020-09-11 19:33:42,748][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:42] "[37mGET /set_filter/none/all/none/no/none HTTP/1.1[0m" 200 -
[2020-09-11 19:33:42,767][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:42] "[37mGET /get_label_value_on_image/none/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:33:42,770][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:42] "[37mGET /marked_image/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:33:43,234][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:43] "[37mGET /set_filter/none/all/none/no/none HTTP/1.1[0m" 200 -
[2020-09-11 19:33:43,235][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:43] "[37mGET /marked_image/undefined HTTP/1.1[0m" 200 -
[2020-09-11 19:33:43,256][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:43] "[37mGET /get_label_value_on_image/none/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:33:43,259][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:43] "[37mGET /marked_image/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:33:43,716][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:43] "[37mGET /marked_image/undefined HTTP/1.1[0m" 200 -
[2020-09-11 19:33:43,731][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:43] "[37mGET /set_filter/none/all/none/no/none HTTP/1.1[0m" 200 -
[2020-09-11 19:33:43,752][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:43] "[37mGET /get_label_value_on_image/none/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:33:43,755][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:43] "[37mGET /marked_image/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:33:44,379][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:44] "[37mGET /marked_image/undefined HTTP/1.1[0m" 200 -
[2020-09-11 19:33:44,398][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:44] "[37mGET /set_filter/none/all/none/no/none HTTP/1.1[0m" 200 -
[2020-09-11 19:33:44,417][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:44] "[37mGET /get_label_value_on_image/none/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:33:44,419][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:44] "[37mGET /marked_image/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:33:45,089][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:45] "[37mGET /marked_image/undefined HTTP/1.1[0m" 200 -
[2020-09-11 19:33:45,112][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:45] "[37mGET /set_filter/none/all/none/no/none HTTP/1.1[0m" 200 -
[2020-09-11 19:33:45,133][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:45] "[37mGET /get_label_value_on_image/none/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:33:45,136][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:45] "[37mGET /marked_image/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:33:47,625][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:47] "[37mGET /set_value/copy_1040_1320279__0804__10_19_12__________.png/none/DELETE HTTP/1.1[0m" 200 -
[2020-09-11 19:33:50,796][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:50] "[37mGET /marked_image/undefined HTTP/1.1[0m" 200 -
[2020-09-11 19:33:50,797][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:50] "[37mGET /set_filter/none/all/none/no/none HTTP/1.1[0m" 200 -
[2020-09-11 19:33:50,821][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:50] "[37mGET /get_label_value_on_image/none/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:33:50,823][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:50] "[37mGET /marked_image/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:33:52,088][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:52] "[37mGET /marked_image/undefined HTTP/1.1[0m" 200 -
[2020-09-11 19:33:52,105][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:52] "[37mGET /set_filter/none/all/none/no/none HTTP/1.1[0m" 200 -
[2020-09-11 19:33:52,131][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:52] "[37mGET /get_label_value_on_image/none/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:33:52,134][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:33:52] "[37mGET /marked_image/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:34:09,930][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:09] "[37mGET /marked_image/undefined HTTP/1.1[0m" 200 -
[2020-09-11 19:34:09,953][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:09] "[37mGET /set_filter/none/all/none/no/none HTTP/1.1[0m" 200 -
[2020-09-11 19:34:09,970][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:09] "[37mGET /get_label_value_on_image/none/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:34:09,971][w3classifier.app][ERROR] - Exception on /marked_image/copy_1040_1320279__0804__10_19_12__________.png [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/views.py", line 35, in marked_image
    jpeg = dbs.marked_image(nm)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/module.py", line 222, in marked_image
    h, w = frame.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
[2020-09-11 19:34:09,975][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:09] "[35m[1mGET /marked_image/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 500 -
[2020-09-11 19:34:12,489][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:12] "[37mGET /set_filter/none/all/none/no/none HTTP/1.1[0m" 200 -
[2020-09-11 19:34:12,508][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:12] "[37mGET /get_label_value_on_image/none/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:34:13,184][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:13] "[37mGET /set_filter/none/all/none/no/none HTTP/1.1[0m" 200 -
[2020-09-11 19:34:13,220][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:13] "[37mGET /get_label_value_on_image/none/copy_1040_1320279__0804__10_19_12__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:34:17,298][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:17] "[37mGET /get_label_value_on_image/none/copy_1095_1346266__0722__10_07_11__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:34:17,300][w3classifier.app][ERROR] - Exception on /marked_image/copy_1095_1346266__0722__10_07_11__________.png [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/views.py", line 35, in marked_image
    jpeg = dbs.marked_image(nm)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/module.py", line 222, in marked_image
    h, w = frame.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
[2020-09-11 19:34:17,302][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:17] "[35m[1mGET /marked_image/copy_1095_1346266__0722__10_07_11__________.png HTTP/1.1[0m" 500 -
[2020-09-11 19:34:17,809][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:17] "[37mGET /get_label_value_on_image/none/copy_1117_1320279__0804__10_19_12_______END.png HTTP/1.1[0m" 200 -
[2020-09-11 19:34:17,812][w3classifier.app][ERROR] - Exception on /marked_image/copy_1117_1320279__0804__10_19_12_______END.png [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/views.py", line 35, in marked_image
    jpeg = dbs.marked_image(nm)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/module.py", line 222, in marked_image
    h, w = frame.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
[2020-09-11 19:34:17,815][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:17] "[35m[1mGET /marked_image/copy_1117_1320279__0804__10_19_12_______END.png HTTP/1.1[0m" 500 -
[2020-09-11 19:34:18,242][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:18] "[37mGET /get_label_value_on_image/none/copy_2158_0540807__0731__14_37_53__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:34:18,244][w3classifier.app][ERROR] - Exception on /marked_image/copy_2158_0540807__0731__14_37_53__________.png [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/views.py", line 35, in marked_image
    jpeg = dbs.marked_image(nm)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/module.py", line 222, in marked_image
    h, w = frame.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
[2020-09-11 19:34:18,247][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:18] "[35m[1mGET /marked_image/copy_2158_0540807__0731__14_37_53__________.png HTTP/1.1[0m" 500 -
[2020-09-11 19:34:18,458][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:18] "[37mGET /get_label_value_on_image/none/copy_2503_0376282__0731__12_20_45__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:34:18,460][w3classifier.app][ERROR] - Exception on /marked_image/copy_2503_0376282__0731__12_20_45__________.png [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/views.py", line 35, in marked_image
    jpeg = dbs.marked_image(nm)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/module.py", line 222, in marked_image
    h, w = frame.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
[2020-09-11 19:34:18,461][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:18] "[35m[1mGET /marked_image/copy_2503_0376282__0731__12_20_45__________.png HTTP/1.1[0m" 500 -
[2020-09-11 19:34:18,930][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:18] "[37mGET /get_label_value_on_image/none/copy_2922_0540807__0731__14_37_53__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:34:18,933][w3classifier.app][ERROR] - Exception on /marked_image/copy_2922_0540807__0731__14_37_53__________.png [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/views.py", line 35, in marked_image
    jpeg = dbs.marked_image(nm)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/module.py", line 222, in marked_image
    h, w = frame.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
[2020-09-11 19:34:18,935][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:18] "[35m[1mGET /marked_image/copy_2922_0540807__0731__14_37_53__________.png HTTP/1.1[0m" 500 -
[2020-09-11 19:34:19,376][w3classifier.app][ERROR] - Exception on /marked_image/copy_4633_1839723__0722__16_58_30_PC_______.png [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/views.py", line 35, in marked_image
    jpeg = dbs.marked_image(nm)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/module.py", line 222, in marked_image
    h, w = frame.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
[2020-09-11 19:34:19,379][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:19] "[37mGET /get_label_value_on_image/none/copy_4633_1839723__0722__16_58_30_PC_______.png HTTP/1.1[0m" 200 -
[2020-09-11 19:34:19,381][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:19] "[35m[1mGET /marked_image/copy_4633_1839723__0722__16_58_30_PC_______.png HTTP/1.1[0m" 500 -
[2020-09-11 19:34:19,794][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:19] "[37mGET /get_label_value_on_image/none/copy_4794_2906477__0724__16_23_07__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:34:19,797][w3classifier.app][ERROR] - Exception on /marked_image/copy_4794_2906477__0724__16_23_07__________.png [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/views.py", line 35, in marked_image
    jpeg = dbs.marked_image(nm)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/module.py", line 222, in marked_image
    h, w = frame.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
[2020-09-11 19:34:19,799][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:19] "[35m[1mGET /marked_image/copy_4794_2906477__0724__16_23_07__________.png HTTP/1.1[0m" 500 -
[2020-09-11 19:34:20,065][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:20] "[37mGET /get_label_value_on_image/none/copy_6787_0376282__0731__12_20_45__________.png HTTP/1.1[0m" 200 -
[2020-09-11 19:34:20,068][w3classifier.app][ERROR] - Exception on /marked_image/copy_6787_0376282__0731__12_20_45__________.png [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/dist-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/views.py", line 35, in marked_image
    jpeg = dbs.marked_image(nm)
  File "/home/imt/work/pyqt5-images-classifier/w3classifier/app/module.py", line 222, in marked_image
    h, w = frame.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'
[2020-09-11 19:34:20,070][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:20] "[35m[1mGET /marked_image/copy_6787_0376282__0731__12_20_45__________.png HTTP/1.1[0m" 500 -
[2020-09-11 19:34:20,275][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:20] "[37mGET /get_label_value_on_image/none/0103_15_07_56_i4981_id276_cn1578064077907896000_thr540.In%20.jpg HTTP/1.1[0m" 200 -
[2020-09-11 19:34:20,281][werkzeug][INFO] - 127.0.0.1 - - [11/Sep/2020 19:34:20] "[37mGET /marked_image/0103_15_07_56_i4981_id276_cn1578064077907896000_thr540.In%20.jpg HTTP/1.1[0m" 200 -
